name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Deploy to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: bitnami
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "."
          target: "/opt/bitnami/apps/music-player"
          strip_components: 0
          
      - name: Install dependencies on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: bitnami
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /opt/bitnami/apps/music-player
            npm install --production
            
      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: bitnami
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cat > /opt/bitnami/apps/music-player/.env << 'EOL'
            NODE_ENV=production
            AWS_REGION=us-east-1
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            CLOUDFRONT_DOMAIN=${{ secrets.CLOUDFRONT_DOMAIN }}
            EOL
            chmod 600 /opt/bitnami/apps/music-player/.env
            
      - name: Update systemd service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: bitnami
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sudo cp /opt/bitnami/apps/music-player/music-player.service /etc/systemd/system/
            sudo chmod 644 /etc/systemd/system/music-player.service
            sudo systemctl daemon-reload
            sudo systemctl restart music-player 